### ISSUE TITLE
Wiki issue on the boolean option entry

### ISSUE THREAD

**Issue by spiralhalo** [grondag/frex#12]
https://github.com/grondag/frex/wiki/Pipeline-Configuration#boolean

It shows the default value `"true"` with quotation marks which I believe is interpreted as string (at least by Jankson) as is causing issues as referenced in https://github.com/vram-guild/canvas/issues/334

And maybe migrate the Wiki to the vram-guild repo as well?

**Comment by grondag** [comment]
Fixed

**Comment by grondag** [comment]
> And maybe migrate the Wiki to the vram-guild repo as well?

This is also done.
